export default {
  Palette: {
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  colors: {
    height: "90%",
  },
  goBack: {
    backgroundColor: "#000",
    width: "20%",
    height: "50%",
    margin: "0 auto",
    display: "inline-block",
    position: "relative",
    cursor: "pointer",
    marginBottom: "-4px",
    textTransform: "uppercase",
    opacity: 1,
    "& a": {
      color: "#fff",
      width: "100px",
      height: "30px",
      position: "absolute",
      display: "inline-block",
      top: "50%",
      left: "50%",
      marginLeft: "-50px",
      marginTop: "-15px",
      textAlign: "center",
      outline: "none",
      background: "rgba(255, 255, 255, 0.3)",
      lineHeight: "30px",
      border: "none",
      fontSize: "0.9rem",
      textTransform: "uppercase",
      cursor: "pointer",
      textDecoration: "none",
    },
  },
};
